config/routes.rb
Rails.application.routes.draw do
  # devise_for :users # , except: %i[destroy]
  # get '/users/sign_out' => 'devise/sessions#destroy'

  root to: 'home#home'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get '/investment/specific', action: 'show', controller: 'investiment'
  get '/investment/edition', action: 'edit', controller: 'investiment'
  post '/investment/updated/', action: 'update', controller: 'investiment'
  get '/investment/destroy', action: 'destroy', controller: 'investiment'
  get 'consortium/edition', action: 'edit', controller: 'consortium'
  post 'consortium/updated', action: 'update', controller: 'consortium'
  get 'consortium/destroy', action: 'destroy', controller: 'consortium'
  resources :investiment, only: %i[index create new]
  resources :consortium, only: %i[index create new]
end

app/controllers/investiment_controller.rb
class InvestimentController < ApplicationController
  before_action :authenticate_user!
  def initialize
    @summary_service = GlobalInvestment.new
    @message = ''
  end

  def index
    @summarys = @summary_service.index
  end

  def show
    @summary = @summary_service.show(params[:invest_id])
  end

  def new; end

  def create
    get_params_create(params['post'])
  end

  def edit
    @summary_edit = @summary_service.show(params[:invest_id])
  end

  def update
    get_params_update(params['post']['invest_id'], params['post'])
  end

  def destroy
    @summary_delete = @summary_service.delete(params['invest_id'])

    @message = if @summary_delete['status'] == 404
                 'usuario já foi excluido'
               else
                 'sucesso ao excluir'
               end
  end

  private

  def get_params_create(params)
    result = json_parser(params)

    @summary_new = @summary_service.create(result)

    @message = if @summary_new['status'] == 201
                 'deu bom meu rapaz'
               else
                 'deu rium meu rapaz'
               end
  end

  def get_params_update(id, params)
    result = json_parser(params)
    @summary_update = @summary_service.update(id, result)
    @message = if @summary_update['status'] == 200
                 'deu bom meu rapaz'
               else
                 'deu rium meu rapaz'
               end
  end

  def json_parser(params)
    {
      "investment_name": params['nome'],
      "status": params['status'],
      "risk": params['risco'],
      "category": params['categoria'],
      "consortium": params['consorcio_id'] || '60b03825fcf1440015381f38',
      "profitability": {
        "day": params['dia'],
        "month": params['mes'],
        "year": params['ano'],
        "score": params['score'],
        "minimum_value": params['minimo']
      }
    }
  end
end

app/helpers/investiment_helper.rb
module InvestimentHelper
end

app/views/investiment/create.html.erb
<h1> <%= @message %> </h1>

<%= link_to "Home", root_path %>

app/views/investiment/destroy.erb
<h1>Tasks#destroy</h1>
<p><%= @message %></p>

app/views/investiment/destroy.html.erb
<h1>Tasks#destroy</h1>
<p><%= @message %></p>

app/views/investiment/edit.erb
<h1>ola</h1>

<%= form_with scope: :post, url: '/investment/updated'   do |form| %>

  <div class="field form-group mb-3">
    <%= form.text_field :invest_id, class:"form-control", value: @summary_edit['response']['_id'], placeholder:"nome do investimento" %>
  </div>

  <div class="field form-group mb-3">
    <%= form.text_field :nome, class:"form-control", value: @summary_edit['response']['investment_name'] , placeholder:"nome do investimento" %>
  </div>
  <div class="field form-group mb-3">
    <%= form.text_field :status, class:"form-control",value: @summary_edit['response']['status'], placeholder:"Open ou Close" %>
  </div>
  <div class="field form-group mb-3">
    <%= form.text_field :risco, class:"form-control",value: @summary_edit['response']['risk'], placeholder:"Moderate, Safe e Severe" %>
  </div>
  <div class="field form-group mb-3">
    <%= form.text_field :categoria, class:"form-control",value: @summary_edit['response']['category'], placeholder:"categoria" %>
  </div>
  <div class="field form-group mb-3">
    <%= form.text_field :consorcio_id, class:"form-control",value: @summary_edit['response']['consortium']['_id'], placeholder:"categoria" %>
  </div>
  <div class="field form-group mb-3">
    <%= form.text_field :dia, class:"form-control",value: @summary_edit['response']['profitability']['day'], placeholder:"dia" %>
  </div>
  <div class="field form-group mb-3">
    <%= form.text_field :mes, class:"form-control",value: @summary_edit['response']['profitability']['month'], placeholder:"mes" %>
  </div>
  <div class="field form-group mb-3">
    <%= form.text_field :ano, class:"form-control",value: @summary_edit['response']['profitability']['year'], placeholder:"ano" %>
  </div>
  <div class="field form-group mb-3">
    <%= form.text_field :score, class:"form-control",value: @summary_edit['response']['profitability']['score'], placeholder:"porcentagem de rentabilidade" %>
  </div>
  <div class="field form-group mb-3">
    <%= form.text_field :minimo, class:"form-control",value: @summary_edit['response']['profitability']['minimum_value'], placeholder:"valor minimo" %>
  </div>


  <br />
    
  <div class="actions">
    
  <%= link_to "ir para investimentos", investiment_index_path %>
  
  <%= form.submit 'Confirmar', class:'btn btn-success' %>

  </div>

<% end %>

app/views/investiment/edit.html.erb
<h1>ola</h1>

<%= form_with scope: :post, url: '/investment/updated'   do |form| %>

  <div class="field form-group mb-3">
    <%= form.text_field :invest_id, class:"form-control", value: @summary_edit['response']['_id'], placeholder:"nome do investimento" %>
  </div>

  <div class="field form-group mb-3">
    <%= form.text_field :nome, class:"form-control", value: @summary_edit['response']['investment_name'] , placeholder:"nome do investimento" %>
  </div>
  <div class="field form-group mb-3">
    <%= form.text_field :status, class:"form-control",value: @summary_edit['response']['status'], placeholder:"Open ou Close" %>
  </div>
  <div class="field form-group mb-3">
    <%= form.text_field :risco, class:"form-control",value: @summary_edit['response']['risk'], placeholder:"Moderate, Safe e Severe" %>
  </div>
  <div class="field form-group mb-3">
    <%= form.text_field :categoria, class:"form-control",value: @summary_edit['response']['category'], placeholder:"categoria" %>
  </div>
  <div class="field form-group mb-3">
    <%= form.text_field :consorcio_id, class:"form-control",value: @summary_edit['response']['consortium']['_id'], placeholder:"categoria" %>
  </div>
  <div class="field form-group mb-3">
    <%= form.text_field :dia, class:"form-control",value: @summary_edit['response']['profitability']['day'], placeholder:"dia" %>
  </div>
  <div class="field form-group mb-3">
    <%= form.text_field :mes, class:"form-control",value: @summary_edit['response']['profitability']['month'], placeholder:"mes" %>
  </div>
  <div class="field form-group mb-3">
    <%= form.text_field :ano, class:"form-control",value: @summary_edit['response']['profitability']['year'], placeholder:"ano" %>
  </div>
  <div class="field form-group mb-3">
    <%= form.text_field :score, class:"form-control",value: @summary_edit['response']['profitability']['score'], placeholder:"porcentagem de rentabilidade" %>
  </div>
  <div class="field form-group mb-3">
    <%= form.text_field :minimo, class:"form-control",value: @summary_edit['response']['profitability']['minimum_value'], placeholder:"valor minimo" %>
  </div>


  <br />
    
  <div class="actions">
    
  <%= link_to "ir para investimentos", investiment_index_path %>
  
  <%= form.submit 'Confirmar', class:'btn btn-success' %>

  </div>

<% end %>

app/views/investiment/home.erb
<h1> <%=@hello%> </h1>

<%= link_to "ir para investimentos", investiment_index_path %>
<%= link_to "criar investimentos", new_investiment_path %>

app/views/investiment/index.erb
<html>
	<body>
	<%= link_to "voltar home", root_path %>

		<h1>Listagem de investimento</h1>

		<% @summarys['response'].each do |summary| %>
		<h2 style="color: #000;">	
			ID:
			<%= summary['_id'] %>
		</h2>
		<h2 style="color: #000;">
			nome do investimento: 
			<%= summary['investment_name'] %>
		</h2>
		<h2 style="color: #000;">
			status:
			<%= summary['status'] %>
		</h2>
		<h2 style="color: #000;">
			risco:	
			<%= summary['risk'] %>
		</h2>
		<h2 style="color: #000;">
			categoria:
			<%= summary['category'] %>
		</h2>
		<h2 style="color: #000;">
			create:	
			<%= summary['created_at'] %>
		</h2>
		<h2 style="color: #000;">	
			update:
			<%= summary['updated_at'] %>
		</h2>
		<h2 style="color: #000;">
			nome do consorcio emissor:	
			<%= summary['consortium']['consortium_name'] %>
		</h2>
		<h2 style="color: #000;">
			dia:	
			<%= summary['profitability']['day'] %>
		</h2>
		<h2 style="color: #000;">
			mes:	
			<%= summary['profitability']['month'] %>
		</h2>
		<h2 style="color: #000;">
			ano:	
			<%= summary['profitability']['year'] %>
		</h2>
		<h2 style="color: #000;">
			score:	
			<%= summary['profitability']['score'] %>
		</h2>
		<h2 style="color: #000;">
			valor minimo:	
			<%= summary['profitability']['minimum_value'] %>
		</h2>

		<%= link_to "Visualizar", investment_specific_path('invest_id' => summary['_id']) %>

		<hr/>
		<% end %>
	</body>
</html>

app/views/investiment/index.html.erb
<!DOCTYPE html>
<html lang="pt-br">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- jQuery -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>

	<!-- Bootstrap CDN-->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
		integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
		crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"
		integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU"
		crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js"
		integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj"
		crossorigin="anonymous"></script>
	<%= stylesheet_link_tag 'investiment' , media: 'all' %>
</head>

<body>
	<div class="container">
		<div class="cardin">
			<h1>Listagem de investimento</h1>
			<%= link_to "voltar home" , root_path, class: 'btn btn-dark' %>
				<%= link_to "criar investimentos" , new_investiment_path, class: 'btn btn-success' %>
		</div>

		<div class="cardin">
			<div class="indicativo">
				<div class="linformativo">
					<div class="container-indicativo">
						<h5>Risco</h5>
						<div>
							<span>
								Baixo
								<i style="background-color: green; color: green;">....</i>
							</span>
							<span>
								Médio
								<i style="background-color: yellow; color: yellow;">....</i>
							</span>
							<span>
								Alto
								<i style="background-color: red; color: red;">....</i>
							</span>
						</div>
					</div>
					<div class="container-indicativo">
						<h5>Status</h5>
						<div>
							<span>
								Fechado
								<i style="background-color: rgb(2, 2, 2); color: rgb(0, 0, 0);">....</i>
							</span>
							<span>
								Aberto
								<i style="background-color: rgb(255, 255, 255); color: rgb(255, 255, 255);">....</i>
							</span>
						</div>
					</div>
				</div>

				<div class="input">
					<div class="search">
						<h2 style="text-align: left;">Ordernação</h2>
						<div>
							<select name="consortium" id="appearance-select">
								<option value="teste">Selecione</option>
								<option value="ASC">Crescente</option>
								<option value="DESC">Decrescente</option>
							</select>
						</div>
					</div>
				</div>

				<div class="input">
					<div class="search">
						<h2 style="text-align: left;">Categoria</h2>
						<div>
							<input type="search" #box1 placeholder="EX: CDB" name="category" id="category">
							<button id="sub" type="submit">
								>
							</button>
						</div>
					</div>

					<div class="input">
						<div class="search">
							<h2 style="text-align: left;">Consócios</h2>
							<div>
								<select name="consortium" id="appearance-select">
									<option value="teste">Selecione</option>
									<option value="teste">teste</option>
									<option value="teste">teste</option>
									<option value="teste">teste</option>
									<option value="teste">teste</option>
								</select>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="cardin">
			<section class="tecnologia">
				<div class="box-linguagem ">
					<div class="box-linguagem-icon">
						<% @summarys['response'].each do |summary| %>
							<div class="box-flex-icon">
								<%= link_to investment_specific_path('invest_id'=> summary['_id']), class: 'link_estilizado' do %>
									<div>
										<% if summary['risk']=='Safe' %>
											<div *ngIf="inves.risk === 'Safe'" class="category" style="background-color: green;">
												<h4>
													<%= summary['category'] %>
												</h4>
											</div>
											<% end %>
												<% if summary['risk']=='Moderate' %>
													<div class="category" style="background-color: yellow; color: black;">
														<h4>
															<%= summary['category'] %>
														</h4>
													</div>
													<% end %>
														<% if summary['risk']=='Severe' %>
															<div class="category" style="background-color: red;">
																<h4>
																	<%= summary['category'] %>
																</h4>
															</div>
															<% end %>
																<div class="header-mat mat-elevation-z2 elevation-z8">
																	<h2>
																		<%= summary['investment_name'] %>
																	</h2>
																</div>
																<div class="bodyCard">
																	<div class="rent_dia">
																		<h4>Rentabilidade anual</h4>
																		<h6>
																			R$ <%= summary['profitability']['day'] %>
																		</h6>
																	</div>
																	<span>Valor minimo: R$ <%= summary['profitability']['minimum_value'] %></span>
																	<div class="atualiza">
																		<span class="atualiza_title">Última atualização:</span>
																		<span class="atualiza_value">
																			<%= summary['updated_at'][0..9].split('-').reverse.join('/')%> às
																				<%= summary['updated_at'][11..15]%>
																		</span>
																	</div>
																</div>
									</div>
									<% if summary['status']=='Open' %>
										<div class="categoryRodape" style="background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);">
											<%= summary['consortium']['consortium_name'] %>
										</div>
										<%end%>
											<% if summary['status']=='Close' %>
												<div class="categoryRodape" style="background-color: rgb(0, 0, 0); color: rgb(255, 255, 255);">
													<%= summary['consortium']['consortium_name'] %>
												</div>
												<%end%>
													<% end %>
							</div>
							<% end %>
					</div>
				</div>
			</section>

		</div>
		<div class="cardin">
			<nav class="pagination_bots" aria-label="Page navigation example">
				<ul class="pagination">
					<li class="page-item"><a class="page-link" href="#">Previous</a></li>
					<li class="page-item"><a class="page-link" href="#">1</a></li>
					<li class="page-item"><a class="page-link" href="#">2</a></li>
					<li class="page-item"><a class="page-link" href="#">3</a></li>
					<li class="page-item"><a class="page-link" href="#">Next</a></li>
				</ul>
			</nav>
		</div>


</body>

</html>

app/views/investiment/new.erb
<h1>ola</h1>



<%= form_with scope: :post, url: '/investiment'   do |form| %>

    <div class="field form-group mb-3">
      <%= form.text_field :nome, class:"form-control", placeholder:"nome do investimento" %>
    </div>
    <div class="field form-group mb-3">
      <%= form.text_field :status, class:"form-control", placeholder:"Open ou Close" %>
    </div>
    <div class="field form-group mb-3">
      <%= form.text_field :risco, class:"form-control", placeholder:"Moderate, Safe e Severe" %>
    </div>
    <div class="field form-group mb-3">
      <%= form.text_field :categoria, class:"form-control", placeholder:"categoria" %>
    </div>
    <div class="field form-group mb-3">
      <%= form.number_field :dia, class:"form-control", placeholder:"dia" %>
    </div>
    <div class="field form-group mb-3">
      <%= form.number_field :mes, class:"form-control", placeholder:"mes" %>
    </div>
    <div class="field form-group mb-3">
      <%= form.number_field :ano, class:"form-control", placeholder:"ano" %>
    </div>
    <div class="field form-group mb-3">
      <%= form.text_field :score, class:"form-control", placeholder:"porcentagem de rentabilidade" %>
    </div>
    <div class="field form-group mb-3">
      <%= form.number_field :minimo, class:"form-control", placeholder:"valor minimo" %>
    </div>
  

    <br />
    
    <div class="actions">
      
    <%= link_to "ir para investimentos", investiment_index_path %>
    
    <%= form.submit 'Confirmar', class:'btn btn-success' %>
  
    </div>
  
<% end %>

app/views/investiment/new.html.erb
<h1>ola</h1>



<%= form_with scope: :post, url: '/investiment'   do |form| %>

    <div class="field form-group mb-3">
      <%= form.text_field :nome, class:"form-control", placeholder:"nome do investimento" %>
    </div>
    <div class="field form-group mb-3">
      <%= form.text_field :status, class:"form-control", placeholder:"Open ou Close" %>
    </div>
    <div class="field form-group mb-3">
      <%= form.text_field :risco, class:"form-control", placeholder:"Moderate, Safe e Severe" %>
    </div>
    <div class="field form-group mb-3">
      <%= form.text_field :categoria, class:"form-control", placeholder:"categoria" %>
    </div>
    <div class="field form-group mb-3">
      <%= form.number_field :dia, class:"form-control", placeholder:"dia" %>
    </div>
    <div class="field form-group mb-3">
      <%= form.number_field :mes, class:"form-control", placeholder:"mes" %>
    </div>
    <div class="field form-group mb-3">
      <%= form.number_field :ano, class:"form-control", placeholder:"ano" %>
    </div>
    <div class="field form-group mb-3">
      <%= form.text_field :score, class:"form-control", placeholder:"porcentagem de rentabilidade" %>
    </div>
    <div class="field form-group mb-3">
      <%= form.number_field :minimo, class:"form-control", placeholder:"valor minimo" %>
    </div>
  

    <br />
    
    <div class="actions">
      
    <%= link_to "ir para investimentos", investiment_index_path %>
    
    <%= form.submit 'Confirmar', class:'btn btn-success' %>
  
    </div>
  
<% end %>

app/views/investiment/show.erb
<h2 style="color: #000;">	
    ID:
    <%= @summary['response']['_id'] %>
</h2>
<h2 style="color: #000;">
    nome do investimento: 
    <%= @summary['response']['investment_name'] %>
</h2>
<h2 style="color: #000;">
    status:
    <%= @summary['response']['status'] %>
</h2>
<h2 style="color: #000;">
    risco:	
    <%= @summary['response']['risk'] %>
</h2>
<h2 style="color: #000;">
    categoria:
    <%= @summary['response']['category'] %>
</h2>
<h2 style="color: #000;">
    create:	
    <%= @summary['response']['created_at'] %>
</h2>
<h2 style="color: #000;">	
    update:
    <%= @summary['response']['updated_at'] %>
</h2>
<h2 style="color: #000;">
    nome do consorcio emissor:	
    <%= @summary['response']['consortium']['consortium_name'] %>
</h2>
<h2 style="color: #000;">
    dia:	
    <%= @summary['response']['profitability']['day'] %>
</h2>
<h2 style="color: #000;">
    mes:	
    <%= @summary['response']['profitability']['month'] %>
</h2>
<h2 style="color: #000;">
    ano:	
    <%= @summary['response']['profitability']['year'] %>
</h2>
<h2 style="color: #000;">
    score:	
    <%= @summary['response']['profitability']['score'] %>
</h2>
<h2 style="color: #000;">
    valor minimo:	
    <%= @summary['response']['profitability']['minimum_value'] %>
</h2>

<%= link_to "Editar", investment_edition_path('invest_id' => @summary['response']['_id']) %>
<br/>
<%= link_to "excluir", investment_destroy_path('invest_id' => @summary['response']['_id']) %>
<br/>
<%= link_to "ir para investimentos", investiment_index_path %>

app/views/investiment/show.html.erb
<h2 style="color: #000;">	
    ID:
    <%= @summary['response']['_id'] %>
</h2>
<h2 style="color: #000;">
    nome do investimento: 
    <%= @summary['response']['investment_name'] %>
</h2>
<h2 style="color: #000;">
    status:
    <%= @summary['response']['status'] %>
</h2>
<h2 style="color: #000;">
    risco:	
    <%= @summary['response']['risk'] %>
</h2>
<h2 style="color: #000;">
    categoria:
    <%= @summary['response']['category'] %>
</h2>
<h2 style="color: #000;">
    create:	
    <%= @summary['response']['created_at'] %>
</h2>
<h2 style="color: #000;">	
    update:
    <%= @summary['response']['updated_at'] %>
</h2>
<h2 style="color: #000;">
    nome do consorcio emissor:	
    <%= @summary['response']['consortium']['consortium_name'] %>
</h2>
<h2 style="color: #000;">
    dia:	
    <%= @summary['response']['profitability']['day'] %>
</h2>
<h2 style="color: #000;">
    mes:	
    <%= @summary['response']['profitability']['month'] %>
</h2>
<h2 style="color: #000;">
    ano:	
    <%= @summary['response']['profitability']['year'] %>
</h2>
<h2 style="color: #000;">
    score:	
    <%= @summary['response']['profitability']['score'] %>
</h2>
<h2 style="color: #000;">
    valor minimo:	
    <%= @summary['response']['profitability']['minimum_value'] %>
</h2>

<%= link_to "Editar", investment_edition_path('invest_id' => @summary['response']['_id']) %>
<br/>
<%= link_to "excluir", investment_destroy_path('invest_id' => @summary['response']['_id']) %>
<br/>
<%= link_to "ir para investimentos", investiment_index_path %>

app/views/investiment/update.erb
<h1><%=@message%></h1>

<%= link_to "ir para investimentos", root_path %>

app/views/investiment/update.html.erb
<h1><%=@message%></h1>

<%= link_to "ir para investimentos", root_path %>