config/routes.rb
Rails.application.routes.draw do
  # devise_for :users # , except: %i[destroy]
  # get '/users/sign_out' => 'devise/sessions#destroy'

  root to: 'home#home'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get '/investment/specific', action: 'show', controller: 'investiment'
  get '/investment/edition', action: 'edit', controller: 'investiment'
  post '/investment/updated/', action: 'update', controller: 'investiment'
  get '/investment/destroy', action: 'destroy', controller: 'investiment'
  get 'consortium/edition', action: 'edit', controller: 'consortium'
  post 'consortium/updated', action: 'update', controller: 'consortium'
  get 'consortium/destroy', action: 'destroy', controller: 'consortium'
  resources :investiment, only: %i[index create new]
  resources :consortium, only: %i[index create new]
end

app/controllers/consortium_controller.rb
class ConsortiumController < ApplicationController
  before_action :authenticate_user!

  def initialize
    @summary_service = GlobalConsortium.new
    @message = ''
  end

  def index
    @summarys = @summary_service.index
  end

  def new; end

  def create
    get_params_create(params['post'])
  end

  def edit
    @summary_show = @summary_service.show(params['conso_id'])
  end

  def update
    get_params_update(params['post']['conso_id'], params['post'])
  end

  def destroy; end

  private

  def get_params_create(params)
    result = json_parser(params)

    @summary_new = @summary_service.create(result)

    @message = if @summary_new['status'] == 201
                 'deu bom meu rapaz'
               else
                 'deu rium meu rapaz'
               end
  end

  def get_params_update(id, params)
    result = json_parser(params)
    @summary_update = @summary_service.update(id, result)
    @message = if @summary_update['status'] == 200
                 'deu bom meu rapaz'
               else
                 'deu ruim meu rapaz'
               end
  end

  def json_parser(params)
    {
      "consortium_name": params['nome']
    }
  end
end

app/helpers/consortium_helper.rb
module ConsortiumHelper
end

app/views/consortium/create.html.erb
<h1>
  <%= @message %>
</h1>

<%= link_to "Home", root_path %>

app/views/consortium/destroy.html.erb
<h1>Consortium#destroy</h1>
<p>Find me in app/views/consortium/destroy.html.erb</p>

app/views/consortium/edit.html.erb
<h1>editar consorio</h1>

<%= form_with scope: :post, url: '/consortium/updated'   do |form| %>

  <div class="field form-group mb-3">
    <%= form.text_field :conso_id, class:"form-control", value: @summary_show['response']['_id'], placeholder:"id do invesimento" %>
  </div>

  <div class="field form-group mb-3">
    <%= form.text_field :nome, class:"form-control", value: @summary_show['response']['consortium_name'], placeholder:"nome do consorcio" %>
  </div>

  <br />
  
  <div class="actions">
    
  <%= link_to "ir para consorcios", consortium_index_path %>
  
  <%= form.submit 'Confirmar', class:'btn btn-success' %>

  </div>

<% end %>

app/views/consortium/index.html.erb
<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- jQuery -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>

  <!-- Bootstrap CDN-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"
    integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js"
    integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj"
    crossorigin="anonymous"></script>
  <%= stylesheet_link_tag 'consortium' , media: 'all' %>
</head>

<body>

  <div class="container">
    <div class="cardin">
      <h1>Lista de Consorcios</h1>
      <p>Emissores de investimentos</p>
      <%= link_to "voltar home" , root_path, class: 'btn btn-dark' %>
        <%= link_to "criar consorcios" , new_consortium_path, class: 'btn btn-success' %>
    </div>


    <div class="cardin">
      <table class="table table-striped">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Nome do emissor</th>
            <th scope="col">Ùltima atualização</th>
            <th scope="col">Ações</th>
          </tr>
        </thead>
        <tbody>
          <% @summarys['response'].each do |summary| %>
            <tr>
              <th scope="row">
                <%= summary['consortium_name'] %>
              </th>
              <td>
                <%= summary['updated_at'][0..9].split('-').reverse.join('/')%> -
                  <%= summary['updated_at'][11..15]%>
              </td>
              <td>
                <%= link_to "Editar" , consortium_edition_path('conso_id'=> summary['_id']), class: 'btn btn-primary' %>
                  <%= link_to "Excluir" , consortium_destroy_path('conso_id'=> summary['_id']), class: 'btn btn-danger'
                    %>
              </td>
            </tr>
            <%end%>
        </tbody>
      </table>
    </div>

    <div class="cardin">
      <nav class="pagination_bots" aria-label="Page navigation example">
        <ul class="pagination">
          <li class="page-item"><a class="page-link" href="#">Previous</a></li>
          <li class="page-item"><a class="page-link" href="#">1</a></li>
          <li class="page-item"><a class="page-link" href="#">2</a></li>
          <li class="page-item"><a class="page-link" href="#">3</a></li>
          <li class="page-item"><a class="page-link" href="#">Next</a></li>
        </ul>
      </nav>
    </div>
  </div>
</body>

</html>

app/views/consortium/new.html.erb
<h1>Criar consorcio</h1>

<%= form_with scope: :post, url: '/consortium'   do |form| %>

    <div class="field form-group mb-3">
      <%= form.text_field :nome, class:"form-control", placeholder:"nome do consorcio" %>
    </div>

    <br />
    
    <div class="actions">
      
    <%= link_to "ir para consorcios", consortium_index_path %>
    
    <%= form.submit 'Confirmar', class:'btn btn-success' %>
  
    </div>
  
<% end %>

app/views/consortium/update.html.erb
<h1>Consortium#update</h1>
<p>Find me in app/views/consortium/update.html.erb</p>
<h1>
  <%= @message %>
</h1>

<%= link_to "Home", root_path %>